accounts/urls.py
from django.urls import path
# viewsモジュールをインポート
from . import views
# viewsをインポートしてauth_viewという記名で利用する
from django.contrib.auth import views as auth_views

# URLパターンを逆引きできるように名前を付ける
app_name = 'accounts'

# URLパターンを登録するための変数
urlpatterns = [
    # サインアップページのビューの呼び出し
    # 「http(s)://<ホスト名>/signup/」へのアクセスに対して、
    # viewsモジュールのSignUpViewをインスタンス化する
    path('signup/',
         views.SignUpView.as_view(),
         name='signup'),
    
    # サインアップ完了ページのビューの呼び出し
    # 「http(s)://<ホスト名>/signup_success/」へのアクセスに対して、
    # viewsモジュールのSignUpSuccessViewをインスタンス化する
    path('signup_success/',
         views.SignUpSuccessView.as_view(),
         name='signup_success'),
    
    # ログインページの表示
    # 「http(s)://<ホスト名>/signup/」へのアクセスに対して、
    # django.contrib.auth.views.LoginViewをインスタンス化して
    # ログインページを表示する
    path('login/',
         # ログイン用のテンプレート(フォーム)をレンダリング
         auth_views.LoginView.as_view(template_name='login.html'),
         name='login'
         ),
    
    # ログアウトを実行
    # 「http(s)://<ホスト名>/logout/」へのアクセスに対して、
    # django.contrib.auth.views.logoutViewをインスタンス化して
    # ログアウトさせる
    path('logout/',
         auth_views.LogoutView.as_view(template_name='logout.html'),
         name='logout'
         ),
]

testapp/urls.py
from django.urls import path
from . import views


# URLパターンを逆引きできるように名前を付ける
app_name = 'testapp'

# URLパターンを登録する変数
urlpatterns = [
    # photoアプリへのアクセスはviewsモジュールのIndexViewを実行
    path('', views.IndexView.as_view(), name='index'),
    path('post/',views.CreateTestView.as_view(),name='post'),
    path('post_done/',
         views.PostSuccessView.as_view(),
         name='post_done'),
    path('tests/<int:category>',
         views.CategoryView.as_view(),
         name='tests_cat'),
    path('user-list/<int:user>',
         views.UserView.as_view(),
         name='user_list'
         ),
    path('test-detail/<int:pk>',
         views.DetailView.as_view(),
         name='test_detail'
         ),
    path('mypage/',views.MypageView.as_view(),name='mypage'),
    path('testapp/<int:pk>/delete/',
          views.TestDeleteView.as_view(),
          name='test_delete'
          ),
     path('contact/',
          views.ContactView.as_view(),
          name='contact'),
]

testproject/urls.py
from django.contrib import admin
from django.urls import path, include # include追加
# auth.viewsをインポートしてauth_viewという記名で利用する
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    
    # photo.urlsへのURLパターン
    path('', include('testapp.urls')),
    
    # accounts.urlsへのURLパターン
    path('', include('accounts.urls')),
    
    # パスワードリセットのためのURLパターン
    # PasswordResetConfirmViewがプロジェクトのurls.pyを参照するのでここに記載
    # パスワードリセット申し込みページ
    path('password_reset/',
         auth_views.PasswordResetView.as_view(
           template_name = "password_reset.html"),
         name ='password_reset'),
    
    # メール送信完了ページ
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(
           template_name = "password_reset_sent.html"),
         name ='password_reset_done'),
    
    # パスワードリセットページ
    path('reset/<uidb64>/<token>',
         auth_views.PasswordResetConfirmView.as_view(
           template_name = "password_reset_form.html"),
         name ='password_reset_confirm'),
    
    # パスワードリセット完了ページ
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(
           template_name = "password_reset_done.html"),
         name ='password_reset_complete'),
]
urlpatterns +=  static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)

testapp/models.py
from django.db import models
from accounts.models import CustomUser
class Category(models.Model):
    title=models.CharField(
        verbose_name='カテゴリ',
    max_length=20)
    def __str__(self):
        return self.title
class TestPost(models.Model):
    user=models.ForeignKey(
        CustomUser,
        verbose_name='ユーザー',
        on_delete=models.CASCADE
    )
    category=models.ForeignKey(
        Category,
        verbose_name='カテゴリ',
        on_delete=models.PROTECT
    )
    title=models.CharField(
        verbose_name='タイトル',
        max_length=200
    )
    comment=models.TextField(
        verbose_name='コメント',
    )
    image1=models.ImageField(
        verbose_name='イメージ1',
        upload_to='tests'
    )
    image2=models.ImageField(
        verbose_name='イメージ2',
        upload_to='tests',
        blank=True,
        null=True
    )
    posted_at=models.DateTimeField(
        verbose_name='投稿日時',
        auto_now_add=True
    )
    def __str__(self):
        return self.title

testapp/forms.py
from django.forms import ModelForm
from .models import TestPost
from django import forms
class TestPostForm(ModelForm):
    class Meta:
        model=TestPost
        fields=['category','title','comment','image1','image2']
class ContactForm(forms.Form):
    name=forms.CharField(label='お名前')
    email=forms.EmailField(label='メールアドレス')
    title=forms.CharField(label='件名')
    message=forms.CharField(label='メッセージ',widget=forms.Textarea)
    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        self.fields['name'].widget.attrs['placeholder']=\
        'お名前を入力してください'
        self.fields['name'].widget.attrs['class']='form_control'
        self.fields['email'].widget.attrs['placeholder']=\
        'メールアドレスを入力してください'
        self.fields['email'].widget.attrs['class']='form-control'
        self.fields['title'].widget.attrs['placeholder']=\
        'タイトルを入力してください'
        self.fields['title'].widget.attrs['class']='form-control'
        self.fields['message'].widget.attrs['placeholder']=\
        'メッセージを入力してください'
        self.fields['message'].widget.attrs['class']='form-control'

testapp/views.py
from django.shortcuts import render
# django.views.genericからTemplateViewをインポート
from django.views.generic import TemplateView,ListView
from django.views.generic import TemplateView
from django.views.generic import CreateView
from django.urls import reverse_lazy
from .forms import TestPostForm
from .forms import ContactForm
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from .models import TestPost
from django.views.generic import DetailView
from django.views.generic import DeleteView
from django.core.mail import EmailMessage
from django.contrib import messages
from django.views.generic import FormView
class ContactView(FormView):
     template_name='contact.html'
     form_class=ContactForm
     success_url=reverse_lazy('testapp:contact')
     def form_valid(self,form):
        name=form.cleaned_data['name']
        email=form.cleaned_data['email']
        title=form.cleaned_data['title']
        message=form.cleaned_data['message']
        subject='お問い合わせ:{}'.format(title)
        message=('送信者名:{0}\nメールアドレス:{1}\n タイトル:{2}\n メッセージ:\n{3}').format(name,email,title,message)
        from_email='kmm2559345@stu.o-hara.ac.jp'
        to_list=['kmm2559345@stu.o-hara.ac.jp']
        message=EmailMessage(subject=subject,
                             body=message,
                             from_email=from_email,
                             to=to_list,)
        message.send()
        messages.success(
            self.request,'お問い合わせは正常に送信されました。')
        return super().form_valid(form)

class IndexView(ListView):
    template_name='index.html'
    queryset=TestPost.objects.order_by('-posted_at')
    paginate_by=9

@method_decorator(login_required,name='dispatch')
class CreateTestView(CreateView):
    form_class=TestPostForm
    template_name='post_test.html'
    success_url=reverse_lazy('testapp:post_done')
    def form_valid(self, form):
        postdata=form.save(commit=False)
        postdata.user=self.request.user
        postdata.save()
        return super().form_valid(form)

class PostSuccessView(TemplateView):
    template_name='post_success.html'

class CategoryView(ListView):
    template_name='index.html'
    paginate_by=9
    def get_queryset(self):
        category_id=self.kwargs['category']
        categories=TestPost.objects.filter(
            category=category_id).order_by('-posted_at')
        return categories

class UserView(ListView):
    template_name='index.html'
    paginate_by=9
    def get_queryset(self):
        user_id=self.kwargs['user']
        user_list=TestPost.objects.filter(
            user=user_id).order_by('-posted_at')
        return user_list

class DetailView(DetailView):
    template_name='detail.html'
    model=TestPost

class MypageView(ListView):
    template_name='mypage.html'
    paginate_by=9
    def get_queryset(self):
        queryset=TestPost.objects.filter(
            user=self.request.user).order_by('-posted_at')
        return queryset

class TestDeleteView(DeleteView):
    model=TestPost
    template_name='test_delete.html'
    success_url=reverse_lazy('testapp:mypage')
    def delete(self,request,*args,**kwargs):
        return super().delete(request,*args,**kwargs)

testapp/templates/base.html
<!-- 静的ファイルのURLを生成するstaticタグをロードする-->
{% load static %}
<!doctype html>
<!-- 言語指定をenからjaに変更-->
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author"
          content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    <!-- ヘッダー情報のタイトルを個別に設定できるようにする-->
    <title>{% block title %}{% endblock %}</title>
    <link rel="icon" type="image/x-icon"
         href={% static 'assets/favicon.ico' %}/>

    <!-- Bootstrap core CSS -->
    <!-- Bootstrap core CSSを読み込むコードをBootstrapからコピー-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
          crossorigin="anonymous">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>    
  </head>
  
  <body>
    <!-- ページのヘッダー-->
    <header>
      <!-- ナビゲーションバーのヘッダー-->
      <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
          <div class="row">
            <div class="col-sm-8 col-md-7 py-4">
              <!-- ヘッダーのタイトルと本文-->
              <h4 class="text-white">お気に入りを見つけよう！</h4>
              <p class="text-muted">
                あなたの知らなかった事を知る機会が今ここに
                ニュースを閲覧したり,投稿したり沢山の種類に
                分かれたニュースをこのサイトで活用しましょう
              </p>
            </div>
            <div class="col-sm-4 offset-md-1 py-4">
              <h4 class="text-white">Contact</h4>
              <ul class="list-unstyled">
                <!-- ナビゲーションメニュー-->
                {% if user.is_authenticated %}
                <!-- ログイン中のメニュー-->
                <li><a href="{% url 'testapp:mypage' %}"
                       class="text-white">マイページ</a></li>
                <li><form method="post" action="{% url 'accounts:logout' %}" style="display:inline;">
                  {% csrf_token %}
                  <button type="submit" class="btn btn-link p-0">ログアウト</button>
                </form></li>
                <li><a href="{% url 'password_reset' %}"
                       class="text-white">パスワードのリセット</a></li>
                <li><a href="{% url 'testapp:contact'%}"
                       class="text-white">お問い合わせ</a></li>
                {% else %}
                <!-- ログイン状態ではない場合のメニュー-->
                <li><a href="{% url 'accounts:signup' %}"
                       class="text-white">サインアップ</a></li>
                <li><a href="{% url 'accounts:login' %}"
                       class="text-white">ログイン</a></li>
                <li><a href="{% url 'testapp:contact'%}"
                       class="text-white">お問い合わせ</a></li>
                {% endif %}
              </ul>
            </div>
          </div>
        </div>
      </div>
      <!-- ナビゲーションバー-->
      <div class="navbar navbar-dark bg-dark shadow-sm">
        <div class="container">
          <!-- トップページへのリンク-->
          <a href="{% url 'testapp:index' %}"
             class="navbar-brand d-flex align-items-center">
            <svg xmlns="http://www.w3.org/2000/svg"
                 width="20" height="20" fill="none"
                 stroke="currentColor"
                 stroke-linecap="round"
                 stroke-linejoin="round"
                 stroke-width="2"
                 aria-hidden="true"
                 class="me-2"
                 viewBox="0 0 24 24">
                 <path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/>
                 <circle cx="12" cy="13" r="4"/></svg>
            <!-- リンクテキスト-->
            <strong>Test Gallery</strong>
          </a>
          <!-- トグルボタン-->
          <button class="navbar-toggler"
                  type="button"
                  data-bs-toggle="collapse"
                  data-bs-target="#navbarHeader"
                  aria-controls="navbarHeader"
                  aria-expanded="false"
                  aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        </div>
      </div>
    </header>
    
    <!-- メインコンテンツ-->
    <main>
      <!-- <main>タグの要素をすべて削除して以下に書き換え-->
      <!-- メインコンテンツの本体部分は各ページのテンプレートで埋め込む-->
      {% block contents %}{% endblock %}
    </main>
    
    <!-- フッター -->
    <footer class="text-muted py-5">
      <div class="container">
        <p class="float-end mb-1">
          <a href="{% url 'testapp:index' %}">Back to top</a>
        </p>
        <!-- フッターのテキストを任意のものに書き換え-->
        <p class="mb-1">
          Test Gallery is &copy; Bootstrap, but please post a lot!</p>
      </div>
    </footer>
    
    <!-- BootstrapからJavaScriptを読み込むコードをコピーして貼り付け-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
            crossorigin="anonymous"></script>      
  </body>
</html>

testapp/templates/contact.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Django's Blog - Contact{% endblock %}
    <body>
        <!-- Navigation-->

        <!-- Page Header-->
         {% block header %}
        <header class="masthead"style="background-image: url({% static 'assets/img/home-bg.jpg' %})">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="page-heading">
                            <h1>Contact Me</h1>
                            <span class="subheading">Have questions? I have answers.</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        {% endblock %}
        <!-- Main Content-->
         {% block contents %}
        <main class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">                   
                        <strong>連絡を取りたいですか?
                            以下のフォームに記入してメッセージを送信してください。
                            できるだけ早くご連絡します。</strong>
                            {% if messages %}
                            <ul class="list-unstyled" style="list-style: none;">
                                {% for message in messages %}
                                <li {%if message.tags %} class="{{message.tags}}"{% endif %}>
                                    {{ message }}
                                </li>
                                {% endfor %}
                            </ul>
                            {% endif %}       
                    <!-- Post preview-->
                    <div class="my-5">
                        <form method="post">
                            {% csrf_token %}
                            {% for field in form %}
                            <div class="form-floating">
                                <div class="form-group floating-label-form-group controls">
                                    {{ field.label_tag }}
                                    {{field}}
                                    <p class="help-block text-danger"></p>
                                </div>
                            </div>
                            {% endfor %}
                            <br>
                            <button type="submit"
                                    class="btn btn-primary"
                                    id="sendMessageButton">Send</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <hr>
        </main>
        {% endblock %}

testapp/templates/detail.html
{% extends 'base.html' %}
{% block title %}Test Detail{% endblock %}
{% block contents %}
<br>
<div class="container">
    <div class="row">
        <div class="col offset-3">
            <h2>{{object.title}}</h2>
            <p>{{object.comment}}</p>
            <br>
            <p>{{object.posted_at}}に投稿</p>
            <p><img src="{{object.image1.url}}"></img></p>
            {% if object.image2 %}
            <p><img src="{{ object.image2.url }}"></img></p>       
            {% endif %}
            {% if request.user == object.user %}
            <form method="POST">
            <a href="{% url 'testapp:test_delete' object.pk %}"
               class="btn btn-primary my-2 ">削除する</a>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

testapp/templates/index.html
<!-- ベーステンプレートを適用する -->
{% extends 'base.html' %}
<!-- ヘッダー情報のページタイトルを設定する -->
{% block title %}Test Gallery{% endblock %}

      {% block contents %}
      
      <!-- タイトルテンプレートの組み込み -->
      {% include "test_title.html" %}

      <!-- 投稿一覧テンプレートの組み込み -->
      {% include "test_list.html" %}

      {% include "pagination.html" %}
      
      {% endblock %}

testapp/templates/mypage.html
{% extends 'base.html' %}
{% block title %}Mypage{% endblock %}
{% block contents %}
{% if user.is_authenticated %}
<br>
<div style="text-align: center;">
    <h4>{{user.username}}さんの投稿されたニュース</h4>
    {% if object_list.count == 0 %}
    <p>{{user.username}}さんの投稿されたニュースはありません</p>
    {% else %}
    <p>投稿<strong>{{object_list.count}}</strong>件</p>
    {% endif %}
    <a href="{% url 'testapp:post' %}">投稿する</a>
</div>
<hr>
{% endif %}
{% include "test_list.html" %}
{% include "pagination.html" %}
{% endblock %}

testapp/templates/pagination.html
<ul class="pagination"
    style="justify-content: center">
{% if page_obj.has_previous %}
<li class="page-item">
    <a class="page-link"
       href="?page={{ page_obj.previous_page_number }}"
       aria-label="Previous">
    <span aria-hidden="true">&laquo;</span>
    </a>
</li>
{% endif %}
{% for num in page_obj.paginator.page_range %}
{% if page_obj.number == num %}
<li class="page-item active">
    <span class="page-link">{{ num }}</span>
</li>
{% else %}
<li class="page-item">
    <a class="page-link" href="?page={{ num }}">{{ num }}</a>
</li>
{% endif %}
{% endfor %}
{% if page_obj.has_next %}
<li class="page-item">
    <a class="page-link"
       href="?page={{ page_obj.next_page_number }}"
       aria-label="Next">
    <span aria-hidden="true">&raquo;</span>
    </a>
</li>
{% endif %}
</ul>

testapp/templates/post_success.html
{% extends 'base.html' %}
{% block title %}Post Success{% endblock %}
{% block contents %}
<br><br>
<div class="container">
    <div class="row">
        <div class="col offset-2">
            <h4>投稿が完了しました!</h4>
        </div>
    </div>
</div>
{% endblock %}

testapp/templates/post_test.html
{% extends 'base.html' %}
{% block title %}Post{% endblock %}
{% block contents %}
<br>
<div class="container">
    <div class="row">
        <div class="col offset-2">
            <form method="POST"
            enctype="multipart/form-data">
        {% csrf_token %}
        <table>
            <tr>
                <th>カテゴリ</th>
                <td>{{form.category}}</td>
            </tr>
            <tr>
                <th>タイトル</th>
                <td>{{form.title}}</td>
            </tr>
            <tr>
                <th>コメント</th>
                <td>{{form.comment}}</td>
            </tr>
            <tr>
                <th>画像1</th>
                <td>{{form.image1}}</td>
            </tr>
            <tr>
                <th>画像2</th>
                <td>{{form.image2}}</td>
            </tr>
        </table>
        <hr>
        <button type="submit">投稿する</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

testapp/templates/test_delete.html
{% extends 'base.html' %}
{% block title %}Test Detail{% endblock %}
{% block contents %}
<br>
<div class="container">
    <div class="row">
        <div class="col offset-3">
            <form method="POST">
                <br>
                <p>削除してもいいですか?</p>
                {% csrf_token %}
                <button class="btn btn-primary my-2"
                        type="submit">削除</button>
                <a href="{% url 'testapp:test_detail' object.pk %}"
                   class="btn btn-secondary my-2">キャンセル</a>
        </div>
    </div>
</div>
{% endblock %}

testapp/templates/test_list.html
  <div class="album py-5 bg-light">
    <!-- Bootstrapのグリッドシステムを適用 -->
    <div class="container">
      <!-- 行要素を配置 -->
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        {% for record in object_list %}
        <!-- 列要素を配置 -->
        <div class="col">
          <div class="card shadow-sm">
            <img src="{{ record.image1.url }}"
                 class="bd-placeholder-img card-img-top"
                 width="100%" height="225"
                 xmlns="http://www.w3.org/2000/svg"
                 role="img" aria-label="Placeholder: Thumbnail"
                 preserveAspectRatio="xMidYMid slice"
                 focusable="false">
                 <title>Placeholder</title>
                 <rect width="100%" height="100%" fill="#55595c"/>
                 <!-- <text>～</text>を削除-->
            </img>
            <!-- タイトルとボタンを出力するブロック -->
            <div class="card-body">
              <p class="card-text">{{record.title}}</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button"
                          class="btn btn-sm btn-outline-secondary"
onclick="location.href='{% url 'testapp:test_detail' record.pk %}'">
                          View</button>
                  <!-- テキストを変更 -->
                  <button type="button"
                          class="btn btn-sm btn-outline-secondary"
onclick="location.href='{% url 'testapp:tests_cat' category=record.category.id %}'">
                          {{record.category.title}}</button>
                </div>
                <!-- <small>タグのテキストを変更-->
                <a href="{% url 'testapp:user_list' user=record.user.id %}">
                  <samll class="text-muted">{{record.user.username}}</samll>
                </a>
              </div>
            </div>
          </div>
        <!-- 列要素ここまで -->
        </div>
        {% endfor %}
      <!-- 行要素ここまで -->
      </div>
    <!-- グリッドシステムここまで -->
    </div>
  </div>

testapp/templates/test_title.html
  <!-- タイトルとナビゲーションボタン -->
  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <!-- タイトルと本文 -->
        <h1 class="fw-light">Test Gallery</h1>
        <p class="lead text-muted">
          ニュースを見て,知識を深めていってください。
          素敵なニュースとコメントをお待ちしています!</p>
        <p>
          <!-- ナビゲーションボタン -->
          <div class="d-flex justify-content-center gap-2"></div>
          {% if user.is_authenticated %}
          <!-- ログイン中のボタン -->
          <a href="{% url 'testapp:post' %}"
             class="btn btn-primary my-2">投稿する</a>
          <form method="post" action="{% url 'accounts:logout' %}" style="display:inline;">
            {% csrf_token %}
            <button type="submit" class="btn btn-secondary">ログアウト</button>
          </form>
          {% else %}
          <!-- ログイン状態ではない場合のボタン -->
          <a href="{% url 'accounts:signup' %}"
             class="btn btn-primary my-2">今すぐサインアップ</a>
          <a href="{% url 'accounts:login' %}"
             class="btn btn-secondary my-2">登録済みの方はログイン</a>
          {% endif %}
        </p>
      </div>
    </div>
  </section>